# Generated by Django 5.0.1 on 2024-02-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heats", "0002_heat_ideal_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="heat",
            name="pool",
            field=models.CharField(
                choices=[("Recreation", "Recreation"), ("Competitive", "Competitive")],
                default="Recreation",
                max_length=25,
            ),
        ),
    ]
