# Generated by Django 5.0.1 on 2024-03-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heats", "0003_heat_pool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heat",
            name="pool",
            field=models.CharField(
                blank=True,
                choices=[("Recreation", "Recreation"), ("Competitive", "Competitive")],
                default="Recreation",
                max_length=25,
                null=True,
            ),
        ),
    ]
