# Generated by Django 5.0.1 on 2024-03-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heats", "0004_alter_heat_pool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heat",
            name="color",
            field=models.CharField(
                help_text="Color hex code with 0x including opacity.",
                max_length=10,
                verbose_name="HEX Color Code",
            ),
        ),
    ]
