# Generated by Django 5.0.1 on 2024-02-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("NB", "Non Binary"),
                    ("U", "Undefined"),
                    ("D", "Gender Diverse"),
                ],
                default="U",
                max_length=12,
            ),
        ),
    ]
