# Generated by Django 5.0 on 2023-12-16 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="date_active_changed",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name="participant",
            name="date_changed",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
