# Generated by Django 5.0.1 on 2024-02-02 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heats", "0003_heat_pool"),
        ("participants", "0002_participant_date_active_changed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="heat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participants",
                to="heats.heat",
            ),
        ),
    ]
