# Generated by Django 5.0.1 on 2024-02-05 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heats", "0003_heat_pool"),
        ("locations", "0001_initial"),
        ("participants", "0003_alter_participant_heat"),
        ("race", "0002_race_date_active_changed_race_date_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="bib_number",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="team",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Team Name"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("user", "race"), name="unique_race_for_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("bib_number", "race"), name="unique_race_for_bib_number"
            ),
        ),
    ]
