# Generated by Django 5.0.1 on 2024-02-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0005_participant_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="location",
            field=models.CharField(
                db_default=models.Value(""), default="", max_length=256
            ),
        ),
    ]
