# Generated by Django 5.0.1 on 2024-02-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0008_alter_participant_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="location",
            field=models.CharField(
                blank=True,
                db_default=models.Value(""),
                default="",
                max_length=256,
                null=True,
            ),
        ),
    ]
