# Generated by Django 5.0.1 on 2024-02-22 23:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heats", "0003_heat_pool"),
        ("locations", "0001_initial"),
        ("participants", "0012_remove_participant_unique_race_for_user_and_more"),
        ("race", "0003_racetype_ftt_allowed_racetype_participants_allowed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelayParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_active_changed",
                    models.DateTimeField(default=datetime.datetime.now, editable=False),
                ),
                ("date_changed", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        db_default=models.Value(""),
                        default="",
                        max_length=256,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RelayTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_active_changed",
                    models.DateTimeField(default=datetime.datetime.now, editable=False),
                ),
                ("bib_number", models.IntegerField(db_index=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Relay Team Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelayTeamComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-creation_date",),
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="participant",
            name="unique_race_for_user",
        ),
        migrations.RemoveConstraint(
            model_name="participant",
            name="unique_race_for_bib_number",
        ),
        migrations.AlterField(
            model_name="participant",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("user", "race"),
                name="unique_participant_per_race_and_user",
                violation_error_message="This user is already registered for this race!",
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("bib_number", "race"),
                name="unique_race_for_participant_bib_number",
                violation_error_message="Another active participant is already using this bib number.",
            ),
        ),
        migrations.AddField(
            model_name="relayparticipant",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="relayparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relayteam",
            name="heat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="relay_teams",
                to="heats.heat",
            ),
        ),
        migrations.AddField(
            model_name="relayteam",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relay_teams",
                to="race.race",
            ),
        ),
        migrations.AddField(
            model_name="relayteam",
            name="race_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relay_teams",
                to="race.racetype",
            ),
        ),
        migrations.AddField(
            model_name="relayparticipant",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participants",
                to="participants.relayteam",
            ),
        ),
        migrations.AddField(
            model_name="relayteamcomment",
            name="relay_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="participants.relayteam",
            ),
        ),
        migrations.AddField(
            model_name="relayteamcomment",
            name="writer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="relayteam",
            constraint=models.UniqueConstraint(
                fields=("name", "race"),
                name="unique_race_for_relay_team_name",
                violation_error_message="This team name is already registered for this race!",
            ),
        ),
        migrations.AddConstraint(
            model_name="relayteam",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("bib_number", "race"),
                name="unique_race_for_relay_team_bib_number",
                violation_error_message="Another active relay team is already using this bib number.",
            ),
        ),
    ]
