# Generated by Django 5.0.1 on 2024-02-24 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("participants", "0013_relayparticipant_relayteam_relayteamcomment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="relayparticipant",
            constraint=models.UniqueConstraint(
                fields=("user", "team"),
                name="unique_relay_participant_for_user_and_team",
                violation_error_message="This user is already registered for this team!",
            ),
        ),
    ]
