# Generated by Django 5.0.1 on 2024-02-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "participants",
            "0014_relayparticipant_unique_relay_participant_for_user_and_team",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="participant",
            name="waiver_signed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="relayparticipant",
            name="waiver_signed",
            field=models.BooleanField(default=True),
        ),
    ]
