# Generated by Django 5.0.1 on 2024-02-29 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0001_initial"),
        ("participants", "0015_participation_participant_waiver_signed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isCheckedIn", models.BooleanField(default=False)),
                ("date_changed", models.DateTimeField(auto_now=True)),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_check_ins",
                        to="checkins.checkin",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RelayTeamCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isCheckedIn", models.BooleanField(default=False)),
                ("date_changed", models.DateTimeField(auto_now=True)),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_check_ins",
                        to="checkins.checkin",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="participants.relayteam",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
