# Generated by Django 5.0.1 on 2024-02-29 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0016_participantcheckin_relayteamcheckin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participantcheckin",
            old_name="isCheckedIn",
            new_name="is_checked_in",
        ),
        migrations.RenameField(
            model_name="relayteamcheckin",
            old_name="isCheckedIn",
            new_name="is_checked_in",
        ),
    ]
