# Generated by Django 5.0 on 2023-12-16 01:13

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("race", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="date_active_changed",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name="race",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="racetype",
            name="date_active_changed",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
