# Generated by Django 5.0.1 on 2024-02-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race", "0003_racetype_ftt_allowed_racetype_participants_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="racetype",
            name="needs_swim_time",
            field=models.BooleanField(default=True),
        ),
    ]
