# Generated by Django 5.0.1 on 2024-02-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0001_initial"),
        ("race", "0004_racetype_needs_swim_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="racetype",
            name="checkins",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="used_by_race_types",
                to="checkins.checkin",
            ),
        ),
    ]
