# Generated by Django 5.0.1 on 2024-02-28 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("positive_action", models.CharField(max_length=256)),
                ("negative_action", models.CharField(max_length=256)),
                (
                    "depends_on",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="checkins.checkin",
                    ),
                ),
            ],
        ),
    ]
