# Generated by Django 5.0 on 2023-12-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
            ],
            options={
                "unique_together": {("city", "province", "country")},
                "index_together": {("city", "province", "country")},
            },
        ),
    ]
